### ISSUE TITLE
[Accounts] CloudFront header forwarding and caching

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#137] opened 2018-11-27 22:11 UTC
### Description
Enumerate the client headers that the backend servers use and which of those change the response from backend servers, so that CloudFront will cache out content effectively.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.j081jnt9w60y

For Unified Reading Experience

### Problem Description
In order for CloudFront to cache content for us, we have to enumerate which headers we want it to forward to our origins.  For the Accounts API, list which headers need to be forwarded to the backend servers by CloudFront and of those say which change the provided response.

### Notes
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html
- Timing: No Later Than Jan 2019
- Blocks: Nothing

### Acceptance Criteria
- Unified team gets a list of headers marked with which impact response content

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by mwharrison** [comment] 2019-06-18 18:33
@jpslav - Is this still something that is needed?

**Comment by jpslav** [comment] 2019-06-25 17:54
Some time back we added forwarding of the `Host` header for the Accounts cache behavior in our distribution.  

We should probably add the `Referer` header as well, as @TomWoodward did for osweb.  We aren't caching Accounts responses (except for assets) so this shouldn't have a cache impact but will allow Accounts to use the request referer.  Thoughts @TomWoodward and @mwharrison ?

**Comment by jpslav** [comment] 2019-06-25 17:55
Referer used here in Accounts: https://github.com/openstax/accounts/blob/085f30cd0c33d9d7c417f64d36f955b1b5ce5f08/app/controllers/sessions_controller.rb#L203

**Comment by TomWoodward** [comment] 2019-06-25 17:56
is there a separate cache behavior for the assets? if so then i don't think there is any harm in forwarding :all-the-things:

**Comment by mwharrison** [comment] 2019-06-25 17:58
I vote yes on adding the referrer. I'm guessing we will cache other things in accounts in the future - one less thing that we'll be scratching our heads about! @jpslav @TomWoodward

**Comment by jpslav** [comment] 2019-06-25 18:14
@TomWoodward there is a separate behavior for assets.  We can add the referer but let's remember that if we do turn on caching later for non-assets, adding the referer header will make the caches referer-specific, which will reduce caching wins.

**Comment by jpslav** [comment] 2019-06-25 19:54
I added the referer in https://github.com/openstax/unified-deployment/pull/38

**Comment by BryanEliDimas** [comment] 2019-07-09 18:04
This issue seems to be a duplicate of #134, except this one has more recent conversation. So I've moved the PR openstax/accounts#655 from 134 to this issue, or in Zenhub terms "re-attached". Just FYI.

**Comment by BryanEliDimas** [comment] 2019-07-09 21:10
@Brooke-Fail I believe there is no way for you to test this. It ended up being just tests within Accounts, actually, AFIK.

**Comment by Brooke-Fail** [comment] 2019-07-12 18:14
Passed QA regression testing, moving to Regression.

**Comment by Brooke-Fail** [comment] 2019-07-16 20:29
Verified in Staging.

**Comment by Brooke-Fail** [comment] 2019-07-17 20:20
Verified in Production.

**Closed by Brooke-Fail** 2019-07-17 20:20 UTC
Labels: Accounts
