### ISSUE TITLE
Implement Institutional Partner Page FE

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#276] opened 2019-02-27 16:13 UTC
# Description
This card is for FE work.

**What is being developed?**
A new web page for the Institutional Partner program.

**Who is the audience for this and what will they be able to do when it is released?**
The audience for this page consists of senior administrators at the institutional level, such as Chancellors, Presidents, Provosts, Vice Chancellors/Presidents of Academic Affairs; OER Coordinators; and Conference organizers. 

When this page is released, they will be able to get detailed information about the Institutional Partner program and its benefits, apply for the program when the application is open, and learn more about the resources OpenStax offers beyond our textbooks.

**Why do it?**
The Institutional Partner program has tremendous benefits for OpenStax. While it coaches institutions on how to adopt all kinds of OER, not just OpenStax, for their students, they are consistently some of our highest ranking schools in terms of adoptions and student savings. See latest IR report here. In addition, the program helps us develop strategic relationships at key institutions. 

**What are the contractual requirements, and/or potential opportunities, and/or risks to be averted?**
If we don’t continue to promote and expand the Institutional Partnership program, there is a risk that institutions will turn to Lumen Learning and other competitors for answers. We need somewhere for schools that are interested in increasing OER use to go for the answers and support they’re looking for. 

**When should it be released?**
Q1 2019

**Why should it be released then?**
We want institutions to have plenty of time to learn more about the program and determine if they should apply before the application opens in late spring 2019.

# Acceptance
There is a page on OpenStax.org under the "What we do" section of the website.
The page is called "Institutional Partnerships"
The page allows a user to download a brochure about the program.
The page allows a user to sign up for more information about the program.
The page allows a user to download an OER Summer Action Plan checklist and links to the Open Oregon Webinar hosted by Nicole.
The page contains the logos of current participants in the program, and a link expands to show the past participant logos.
During the application season, the page has a button taking users to the Institutional Partnership application page.

Additional Acceptance Criteria:
- The newly designed page replaces the current page listed under the "What we do" section of openstax.org.
- The new page's url is: https://openstax.org/institutional-partnership 
- The Institutional Partner Application url is changed to  https://openstax.org/institutional-partnership-application

# Epic Doc

https://docs.google.com/document/d/1P7lrNh7zSDXspphYA2AUyIMxXNdAB5tUkOxX6wus1XQ/edit#heading=h.wuc3pn1ckk21

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by victoria-cooke** [comment] 2019-02-28 21:24
Hi-Fi: https://invis.io/98QRRWRSVUN#/349639524_20190208_BIT_IPPWebpage_VCooke_v2-00

**Comment by victoria-cooke** [comment] 2019-03-15 19:32
@RoyEJohnson Web and mobile are up on Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627?seid=5c8bfaeb0ffc6f25259b6b61

**Comment by RoyEJohnson** [comment] 2019-03-22 20:37
Moved to Blocked because: waiting for BE. Should have it Mar 25 or so.

**Comment by victoria-cooke** [comment] 2019-03-25 13:00
@RoyEJohnson The design was changed on both mobile and web slightly. Updates have been posted to Zeplin. Also, the partner section link will probably have some special behavior. Currently waiting for @allisonhowell to approve the design.

**Comment by laurenloh** [comment] 2019-04-12 20:25
@RoyEJohnson I was trying to input the 'established partners' in the cms on dev for this page - however, any link that I enter into the section does not show up
[Screen Shot 2019-04-12 at 3.22.48 PM.png](https://images.zenhubusercontent.com/5bc0fa2c368ff742e4c2b034/93581b46-588e-425a-8cce-bf3017c848e7)

**Comment by victoria-cooke** [comment] 2019-04-17 16:27
@RoyEJohnson @allisonhowell UX review cards are up: https://trello.com/b/Vr2DfPT7/ux-review-footer-ip-program

**Comment by Brooke-Fail** [comment] 2019-04-30 18:51
There are still a few issues with this:
1. Link for Download this brochure in the About this Program section does not take the user to the proper place. 
2. Clicking Submit after inputting an email to Sign up for Updates links the user to an example url
3. Clicking on Established Partners opens the list of partners underneath the last two sections. (See video)
Video:
https://drive.google.com/file/d/1cm5twuIkRKkZYrdtCR7j7-SOdYYFQxqr/view?usp=sharing

**Comment by allisonhowell** [comment] 2019-05-03 17:25
@victoria-cooke tagging you just so you know this is back in design per the updates we discussed.

**Comment by victoria-cooke** [comment] 2019-05-07 19:27
@allisonhowell @RoyEJohnson design has been updated and placed on Zeplin with notes. 
https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/screen/5cd1db1c7a40b8038f95c230

Changes:
- Hero image
- Sign up section

**Comment by RoyEJohnson** [comment] 2019-05-08 15:17
Updated banner image and sign-up text in CMS
Using form-submit address as target of Sign up button link (currently example.com/formSubmit, but can be changed in the CMS)

**Comment by allisonhowell** [comment] 2019-05-11 02:05
@victoria-cooke For review. Can you move it to UX Review Done once you've approved?

**Comment by victoria-cooke** [comment] 2019-05-13 14:19
@RoyEJohnson @allisonhowell Changes have been added to the Trello board at https://trello.com/b/Vr2DfPT7/ux-review-ip-program.

**Comment by Brooke-Fail** [comment] 2019-05-16 20:34
The only issue is the link for download this brochure is still set to example domain. 
@allisonhowell  will need to fix this.  Moving to Regression in the mean time. I do not think there will need to be another deploy for this fix. If one is needed, I will quickly verify in QA.

**Comment by CaptainXep** [comment] 2019-05-17 20:28
Verified in Staging

**Comment by Brooke-Fail** [comment] 2019-05-21 14:27
Verified in Staging, including Allison's fixes.

**Comment by itsgeraldwang** [comment] 2019-05-22 14:16
Verified in Production

**Closed** 2019-05-22 14:16 UTC
Labels: ux-bit, ux-pts-01
