### ISSUE TITLE
[Accounts] Students are able to access OAuth applications page.

### ISSUE THREAD

**Issue by jessicatelles** [openstax/business-intel#148] opened 2018-12-04 16:35 UTC
@jessicatelles commented on [Tue Oct 23 2018](https://github.com/openstax/bit-backlog/issues/18)

Trello: https://trello.com/c/17n0sQvn/892-accounts-students-are-able-to-access-oauth-applications-page

Description
-- 
SCENARIO
When logged in as a student, you can visit the page https://accounts-dev.openstax.org/oauth/applications

Even though a student cannot do anything on this page, they should not be able to access it. It should instead return a ~404~ 403**.

You can test with student01.

** Edit: [Bryan] Originally this card said to return a 404 but I believe that the more correct behavior is to return a 403.

Steps to Reproduce the issue: Who, Where and How?

Product:
[ ] Accounts [ ] BigLearn
[ ] Exercises [ ] CNX
[ ] Payments [ ] Tutor
[ ] Highlight [ ] Web
User Type:
[ ] Admin [ ] Content/QA
[ ] Student [ ] Teacher
[ ] N/A
Username:
URL:
Course number:
Course type:

Steps

Environment:

Instance:
[ ] production [ ] qa [ ] staging
[ ] dev [ ] content [ ] demo
OS:
[ ] Mac OSX [ ] Windows
[ ] Android [ ] iOS
Browser:
[ ] Chrome [ ] Firefox [ ] Safari
[ ] Opera [ ] IE [ ] Edge
Browser Version:
Possible impact on a User:

Images or Screenshots (attach below)

UX Review & Feature Test
--
- [ ] Ready for UX Review
- [ ] UX Review completed
- [ ] Ready for Functional Test
- [ ] Functional Test completed

Checklist for Done
--

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by jpslav** [comment] 2019-03-14 04:37
@mwharrison is this a dupe of other cards?

**Comment by BryanEliDimas** [comment] 2019-06-20 03:36
I'm 99% sure that the problem has already been solved by Karina in PR https://github.com/openstax/accounts/pull/649.

**Comment by BryanEliDimas** [comment] 2019-06-20 03:42
> I'm 99% sure that the problem has already been solved by Karina in PR openstax/accounts#649.

@mwharrison, could you please confirm? I had to dig through the code and understand the whole range of possibilities, with additional confusion because of a lack of PR description, nebulous issue description, and less than ideal commit messages... TBH.

**Comment by Brooke-Fail** [comment] 2019-06-26 14:17
Verified in QA.

**Comment by Brooke-Fail** [comment] 2019-06-28 17:10
Verified in Staging.

**Comment by Brooke-Fail** [comment] 2019-07-01 14:07
Verified in Production.

**Closed** 2019-07-01 14:07 UTC
Labels: Accounts, priority1-high
