### ISSUE TITLE
Implement User ID tracking for Google Analytics (Footer notification) 

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#501] opened 2019-07-15 18:47 UTC
# Description
This is the second half of the work related to User ID Tracking: https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/business-intel/268
# Acceptance Criteria
Design: https://invis.io/JVSHBM1XTB6#/369678511_20190612_BIT_IDTracking_VCooke_v3-01
- The cookie is only used when someone logs in, so we will only display the message to logged in users - either if they arrive on the page logged in or when they log in. 
- The message will be displayed on the landing page in the session. If a user navigates away from the landing page it will disappear.
- It will continue to display each time a logged in user goes to openstax.org, until they click that they've "got it."
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by victoria-cooke** [comment] 2019-07-17 14:48
@allisonhowell Updated screen: https://invis.io/JVSHBM1XTB6#/369678511_20190612_BIT_IDTracking_VCooke_v3-02

**Comment by allisonhowell** [comment] 2019-07-17 15:59
@victoria-cooke Can you change the language to "This site uses cookies to optimize your experience when logged in to our platform. By continuing to use this site, you agree to our use of cookies. You can find more information in our Privacy Policy.

**Comment by victoria-cooke** [comment] 2019-07-17 16:35
@allisonhowell Updated

**Comment by victoria-cooke** [comment] 2019-07-18 15:24
@RoyEJohnson Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=5d308ed1c0676c5182f06cba

**Comment by allisonhowell** [comment] 2019-07-19 16:52
@RoyEJohnson new language:


"We use cookies to optimize your experience on our website. By continuing on the website, you are agreeing to our use of cookies. You can find more information, including how to opt out, in our Privacy Policy."

**Comment by allisonhowell** [comment] 2019-07-22 17:32
@RoyEJohnson I just looked at this on dev. Users should still be able to navigate the site without clicking anything. cc: @victoria-cooke

**Comment by victoria-cooke** [comment] 2019-07-31 15:19
@RoyEJohnson Review items on Trello under the **ID Tracking** label: https://trello.com/b/Vr2DfPT7/ux-review-openstax-logo-rover-page-book-banners-rover-pop-up-user-id-tracking

**Comment by kjdav** [comment] 2019-08-02 20:45
Hi, I have some questions about the behavior (so we can emulate in REX): 

If a user clicks the x or navigates to a new page in the same session, does it disappear and never shows up again in the same session? 

If that person above leaves and comes back 1 day later to the same tab, should it appear? 

If that person above closes the tab and comes back to an openstax url, should it appear? 

The only logged in users who should never see it are users who at one point clicked "got it"? 

My understanding is that there's no requirement that REX have the exact same cookie notification style as y'all have. If that's incorrect, let me know. 

Thank you! @RoyEJohnson @allisonhowell @victoria-cooke

**Comment by kjdav** [comment] 2019-08-02 21:03
Also, how important is it to have the x (that allows you to dismiss without accepting)? The message says you accept it by continuing to use the site.

**Comment by RoyEJohnson** [comment] 2019-08-02 21:08
We're removing the put-away x.
If the user clicks Got It, a cookie gets set so that the notice never shows up again.
If the notice goes away due to navigating away, it will show up the next time the site is loaded.

**Comment by victoria-cooke** [comment] 2019-08-07 21:37
@RoyEJohnson A couple of small changes and this should be good to go: https://trello.com/b/Vr2DfPT7/ux-review-rover-page-book-banners-rover-pop-up-user-id-tracking-study-edge-blog-search-get-the-book-menu?menu=filter&filter=label:ID%20Tracking

**Comment by Brooke-Fail** [comment] 2019-08-08 18:07
So far the only issue is that the Privacy Policy link does not work: https://cms-qa.openstax.org/privacy. I will verify the fix for this and any other small changes added.

**Comment by Brooke-Fail** [comment] 2019-08-08 19:03
Verified in QA.

**Comment by Brooke-Fail** [comment] 2019-08-12 19:00
Verified that the code is turned off in QA and Staging now.

**Comment by kjdav** [comment] 2019-08-13 16:46
Given the decisions from last week to geofence users in the 44 EEUA countries, are these the new acceptance criteria @allisonhowell ? 

- Do not set the user id tracking cookie if the user is in one of the 44 EEUA countries (i.e., do not track those users)
- Do not show the cookie notification if the user is in one of the 44 EEUA countries

**Comment by allisonhowell** [comment] 2019-08-13 16:55
@kjdav Yes, that's correct!

**Comment by Brooke-Fail** [comment] 2019-08-14 15:52
Verified that this is not currently user facing and is "turned off" in Production.

**Comment by kjdav** [comment] 2019-08-15 12:34
Just adding a note so I can look back here if I forget: I confirmed with Allison that for users who are NOT in the EEUA countries: we will show the notice to logged in users and track user ID’s regardless of whether they accept the notice or not.

**Comment by Brooke-Fail** [comment] 2019-09-04 16:47
This has been verified in QA. However there is a rare issue that can occur. The use could get the cookie with a grayish film behind it. If this happens the user must reload their browser, otherwise they wont be able to click any other buttons after they click "got it".

rare issue with grayish film:
(mobile view)
![Screenshot_20190904-103706_Chrome](https://user-images.githubusercontent.com/48449285/64274799-bf246700-cf09-11e9-9152-f047d310dd2a.jpg)

how it should look:
(mobile view)
![Screenshot_20190904-114541_Samsung Internet](https://user-images.githubusercontent.com/48449285/64274806-c64b7500-cf09-11e9-9bca-89204dab0c4e.jpg)

**Comment by Brooke-Fail** [comment] 2019-09-06 15:05
Verified in Staging.

**Comment by Brooke-Fail** [comment] 2019-09-11 14:12
Verified in Production.

**Closed by Brooke-Fail** 2019-09-11 14:12 UTC
Labels: ux-bit, ux-pts-03
