### ISSUE TITLE
[Accounts] Set cache headers on responses

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#134] opened 2018-11-27 21:45 UTC
### Description
Set cache headers on responses so that content is cached within CloudFront for an appropriate amount of time.

For Unified Reading Experience

### Problem Description
CloudFront decides how long to cache content based on settings within the distribution and headers returned from the Accounts origin (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html).  Need to make sure that we’re setting headers on responses that indicate how long to cache objects in CloudFront.

### Notes
- *Do not publicly cache /api/user!*
- Timing: Nice to have at least thought through this prior to the Rex release, but isn’t required; if we set cache durations in the distribution and have the cache invalidation story complete, we can get by without this.  
- Blocks: Nothing

### Acceptance Criteria
- Spot check that headers are set on responses.  
- Write tests to verify that cache headers are set

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by jpslav** [comment] 2019-03-14 04:32
I think cache headers are set correctly on responses, e.g. go to accounts-qa.openstax.org, and log in as student01.  Look in the Chrome inspector on the Network tab and see that everything except for Rails assets has `Cache-Control: max-age=0, private, must-revalidate` and assets have `Cache-Control: max-age=31536000, public`.  See [this Heroku post](https://devcenter.heroku.com/articles/http-caching-ruby-rails) about the parts of Rails that do this.  

So there may be no work for setting the headers appropriately, but it would be great if we could write specs that are locking down this behavior.  E.g. showing that `/api/user` has the "don't cache me" headers.  Or a spec that shows that all routes except for assets have this, or some helper spec method that will let us add in a quick spec in existing spec files to test this behavior for important endpoints/pages.  I gave this a quick shot and it wasn't as easy as I had hoped.  We can discuss it further and brainstorm.

**Comment by KarinaMendez2** [comment] 2019-03-28 18:14
Finished specs, @jpslav will need to check that the header values as proven in the specs yield the behavior we want with respect to the AWS documentation.

**Comment by BryanEliDimas** [comment] 2019-07-09 18:02
This issue (134) appears to be a duplicate of #137. I moved the PR accordingly, so I'm closing this one.

**Closed by BryanEliDimas** 2019-07-09 18:02 UTC
Labels: Accounts, story
