### ISSUE TITLE
Implement search/filter on the openstax.org blog

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#461] opened 2019-06-26 14:39 UTC
# Description
As a reader of the OpenStax blog, I want to filter blog post so that I can find and share content that is most relevant to me. 

# Acceptance Criteria
- Users can search blog posts by keyword
- Users can filter blog posts by the following:
         Tag/Keyword
         Author
         Month of publication
         If a user filters by a particular author, the results include any posts that contain their name in the 
         author field - whether they are sole author, coauthor, or editor (i.e. filtering for Mary K. Allen would 
         return posts by Mary K. Allen, posts by Mary K. Allen and Alina Slavik, and posts by Daniel 
         Williamson, ed. Mary K. Allen if those all existed)
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment] 2019-06-26 14:40
@victoria-cooke Here is the mockup for this work that was done awhile before you joined the team: http://aizpfs.axshare.com/#g=1&p=news_search_results_-_visual_design

We should discuss this one, too.

**Comment by berkalpyakici** [comment] 2019-07-19 15:07
@RoyEJohnson Backend work is done for search. You can use the get parameter `?q=Search text goes here` to make search queries on blog posts.

**Comment by victoria-cooke** [comment] 2019-08-05 15:35
@RoyEJohnson UX review items: https://trello.com/b/Vr2DfPT7/ux-review-rover-page-book-banners-rover-pop-up-user-id-tracking-study-edge-blog-search?menu=filter&filter=label:Blog%20Search

**Comment by victoria-cooke** [comment] 2019-08-07 21:13
@RoyEJohnson Perfect, this is good to go.

**Comment by Brooke-Fail** [comment] 2019-08-09 14:28
The code for this is going out, however there is a PR that hides this from the user (intended for this release). Verified the current code that it is hidden in QA.

**Comment by Brooke-Fail** [comment] 2019-08-12 18:59
Verified the current code that it is hidden in Staging.

**Comment by Brooke-Fail** [comment] 2019-08-14 15:49
Verified that this is hidden and not currently user facing in Production.

**Comment by Brooke-Fail** [comment] 2019-08-22 14:33
Code is currently hidden in QA for the 8/28 release, as intended.

**Comment by Brooke-Fail** [comment] 2019-09-05 16:03
Verified in QA. There are a few issues with blog search, like searching the first or last name for an editor. This issue is being tracked here: https://github.com/openstax/business-intel/issues/630. Moving to regression.

**Comment by Brooke-Fail** [comment] 2019-09-06 18:36
Verified in Staging.

**Comment by Brooke-Fail** [comment] 2019-09-11 13:57
Verified in Production.

**Closed by Brooke-Fail** 2019-09-11 13:57 UTC
Labels: OSWeb, kd-search-traffic, ux-bit
